---
# tasks file for rbenv

- name: 'use yum if package manager is yum'
  include: './yum.yml'
  when: ansible_pkg_mgr == 'yum'
  static: no

- name: 'use apt if package manager is apt'
  include: './apt.yml'
  when: ansible_pkg_mgr == 'apt'
  static: no

- name: 'create opt directory'
  file:
    path: '${HOME}/opt'
    state: 'directory'
    follow: yes
  become: yes
  become_user: "{{ rbenv_user }}"

- name: 'create tmp directory'
  file:
    path: '${HOME}/tmp'
    state: 'directory'
    follow: yes
  become: yes
  become_user: "{{ rbenv_user }}"


- name: 'install archives'
  block:
  - name: 'get archives'
    get_url:
      url: "{{ item.src }}"
      dest: "${HOME}/tmp/{{ item.name }}-{{ item.src | basename }}"
      backup: no
      force: yes
      # checksum: "{{ item.checksum }}"
      timeout: 30
      validate_certs: yes
    changed_when: false
    with_items: "{{ rbenv_archives }}"

  - name: 'extract archives'
    unarchive:
      src: "${HOME}/tmp/{{ item.name }}-{{ item.src | basename }}"
      dest: "${HOME}/opt"
      remote_src: yes
      keep_newer: no
    with_items: "{{ rbenv_archives }}"
    ignore_errors: "{{ ansible_check_mode }}"

  - name: 'delete archives'
    file:
      path: "${HOME}/tmp/{{ item.name }}-{{ item.src | basename }}"
      state: 'absent'
      follow: yes
    changed_when: false
    with_items: "{{ rbenv_archives }}"

  become: yes
  become_user: "{{ rbenv_user }}"


- name: 'setup rbenv with ruby-build'
  block:
  - name: 'create simlink to current version'
    file:
      src: "${HOME}/opt/{{ item.src | regex_replace( '^[^/]+://github\\.com/[^/]+/([^/]+)/archive/v([^/]+)\\.tar\\.gz$', '\\1-\\2' ) }}"
      path: "${HOME}/opt/{{ item.name }}"
      state: 'link'
      follow: yes
      force: yes
    with_items: "{{ rbenv_archives }}"

  - name: 'create plugins directory'
    file:
      path: '${HOME}/opt/rbenv/plugins'
      state: 'directory'
      follow: yes

  - name: 'create simlink to ruby-build'
    file:
      src: '${HOME}/opt/ruby-build'
      path: '${HOME}/opt/rbenv/plugins/ruby-build'
      state: 'link'
      follow: yes
      force: yes

  - name: 'create simlink to rbenv'
    file:
      src: '${HOME}/opt/rbenv'
      path: '${HOME}/.rbenv'
      state: 'link'
      follow: yes
      force: yes

  become: yes
  become_user: "{{ rbenv_user }}"


- name: 'setup .bash_profile'
  block:
  - name: 'add keywords to .bash_profile'
    lineinfile:
      path: '${HOME}/.bash_profile'
      state: present
      create: yes
      validate: '/bin/bash %s'
      insertafter: EOF
      line: "{{ item.keyword }}"
    with_items: "{{ rbenv_bash_profile }}"

  - name: 'add commands to .bash_profile'
    lineinfile:
      path: '${HOME}/.bash_profile'
      state: present
      validate: '/bin/bash %s'
      insertafter: "{{ item.keyword | regex_escape() }}"
      regexp: "{{ item.regexp | default( '.*' ) }}"
      line: "{{ item.line }}"
    when: 'item.line is defined'
    with_items: "{{ rbenv_bash_profile }}"

  become: yes
  become_user: "{{ rbenv_user }}"
